tier4/caret

ansible/roles/ros-tracing/tasks/main.yml
I'd like to merge this change because python3-bt2 is required for current version of CARET.
=> fix(ros-tracing): add python3-bt2

ansible/roles/caret/tasks/main.yml
- ROS2 Galactic becomes end-of-life, and packages for Galactic is not installed by default. It causes error at `./setup_caret.sh`
- This PR adds `rosdep install` option to include end-of-life distributions
https://github.com/ros/rosdistro/pull/35599
- This is only for `galactic` branch
- We may stop supporting Galactic when another problem happens in the future
- Spell check error happens. It's probably because dictionary settings is not included in `galactic` branch. I think we can ignore this error for now
=> fix: setup for Galactic

.github/pull_request_template.md
Signed-off-by: takeshi.iwanari <takeshi.iwanari@tier4.jp>
- This PR fixes link to the community guideline in PR template which was added by https://github.com/tier4/caret/pull/57
https://github.com/tier4/caret/pull/57
=> docs: fix link to community guideline in PR template

ansible/roles/caret/templates/setenv_caret.bash.jinja2
Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>
I want to add ulimit explanation to setenv_caret.bash.
After updating LTTng from 2.12 to 2.13, users have to mind the maximum number of file descriptor. I think that setenv_caret.bash must have some description for users to notice it. 
https://tier4.github.io/CARET_doc/latest/recording/recording/#starting-lttng-session-manually
> You may find that size of recorded data is strangely smaller than expected after updating LTTng to 2.13 if you apply CARET to a large application like [Autoware](https://github.com/autowarefoundation/autoware) which has hundreds of nodes. You have to suspect that maximum number of file descriptors is not enough in the case. You can check the number with ulimit -n command. The default maximum number is …
=> chore(ansible): add ulimit execution to setenv_caret.bash

docker/build_autoware.dockerfile
Signed-off-by: takeshi.iwanari <takeshi.iwanari@tier4.jp>
- This PR ignores  "all warnings being treated as errors" 
- Otherwise, build error occurs. e.g. https://github.com/tier4/caret/actions/runs/3998568645
- It's caused by code in Autoware, and I'd like to ignore it to continue our test
None
- For ` The PR has been properly tested.` you can check the following result
- https://github.com/tier4/caret/actions/runs/4002305430
=> ci: fix build error by warnings

.github/CONTRIBUTING.md, .github/workflows/build_autoware.yaml, docker/README.md, docker/build_autoware.dockerfile
- Fix CI (build_with_autoware) failure
- Use the current version (branch) of CARET instead of main branch
- (Fix  pre-commit-optional , broken link)
- Before (failed): https://github.com/tier4/caret/actions/runs/4306007450
- After (passed): https://github.com/tier4/caret/actions/runs/4311911216
None
=> ci: fix build with autoware

release_script/release_caret.sh
- Commit message for release has unnecessary double quotation. It violates commit message naming rule
- ![image](https://github.com/tier4/caret/assets/105265012/f4116029-9530-4b3a-90ed-b2dd71b140ea)
- This PR removes it
None
It would be great if you test it when you release CARET next time
=> chore: fix release commit message

docker/build_autoware.dockerfile
This PR fixes CI (Build with Autoware). It failed 2023/09/13 because locale package 2.35-0ubuntu3.1 cannot be installed. This PR update local version to be installed
- main as of 2023/09/13: https://github.com/tier4/caret/actions/runs/6175555552
- with this PR: https://github.com/tier4/caret/actions/runs/6178498060
None
None
=> ci: fix Build with Autoware test

ansible/playbook.yml, ansible/roles/cyclonedds/tasks/main.yml, caret.repos
Since version `v0.10.x` of cyclonedds, function hooks are no longer possible due to the addition of a description that hides symbols. Include Cyclone DDS in ros2_caret_ws and disable certain descriptions in order to be able to hook Cyclone DDS functions.
- Directories: 
```
└── src
├── CARET
├── eclipse-cyclonedds
├── ros-tracing
└── ros2
```
- How to disable symbol hiding process
- Just comment out `set_property(TARGET ddsc PROPERTY C_VISIBILITY_PRESET hidden)`
=> feat: added cyclonedds

ansible/roles/caret/templates/setenv_caret.bash.jinja2
setenv_caret.bash to daemonize if the lttng session is not started
https://tier4.atlassian.net/browse/RT2-973
=> fix: daemonize if lttng session is not running

.github/workflows/build_autoware.yaml, docker/build_autoware.dockerfile
This PR fixes CI (Build with Autoware) failure by disabling cache for Docker.
Building Autoware failed even without CARET but a new PR fixes the error recently, but the new PR is not reflected in our CI due to cache. That's why CI kept failed.
None
None
=> ci: don't use cache to build with Autoware

docker/build_autoware.dockerfile
Fix usage of the `ros2caret` command.
Cahnged from `ros2 caret check_caret_rclcpp --workspace ./` to `ros2 caret check_caret_rclcpp ./`
- https://github.com/tier4/ros2caret/pull/129
=> fix(docker): ros2caret_usage

docker/build_autoware.dockerfile
=> fix: build with autoware

ansible/roles/caret/tasks/main.yml, ansible/roles/caret_iron/tasks/main.yml, ansible/roles/ros-tracing/tasks/main.yml, ansible/roles/visualizer/tasks/main.yml, setup_caret.sh
The requirements.txt in caret is installed with user privileges.
[https://tier4.atlassian.net/browse/RT2-1874](https://tier4.atlassian.net/browse/RT2-1874)
=> fix: the requirements.txt in caret is installed with user privileges.

setup_caret.sh
Increase the version of ansible to “6*” to match autoware.
[https://tier4.atlassian.net/browse/RT2-1874](https://tier4.atlassian.net/browse/RT2-1874)
=> fix: ansible update to version 6*

ansible/roles/caret/templates/setenv_caret.bash.jinja2, ansible/roles/caret_iron/templates/setenv_caret.bash.jinja2
This fixes to leave the existing values in the set part of `LD_PRELOAD`. 
[Related Thread in Slack (TIER IV internal)](https://star4.slack.com/archives/C07FL8616EM/p1732776202743879?thread_ts=1732752446.741309&cid=C07FL8616EM)
=> fix: add current value for LD_PRELOAD

caret.repos
- Background
- [topic_tools](https://github.com/ros-tooling/topic_tools) is a widely used package
- This package is installed by apt and a pre-built package, therefore an application using such package cannot be traced by CARET, especially path analysis doesn't work
- Changes
- Build topic_tools along with CARET
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-2211)
- This change is needed only for Humble, because an application no longer needs to be build with caret/rclcpp after Iron where trace points by CARET are implemented into ros/rclcpp
- I considered to separate repos file. For instance, topic_tools can be added into a new repo file named vendor.repos. However, I decided to aggregate them to make it simple and easy to use
The PR reviewers **must** check the …
=> chore: add topic_tools repo

release_script/release_caret.sh, release_script/template_caret.repos
Modify the following release scripts to incorporate the topic_tools package into caret.
- release_script/release_caret.sh
- release_script/template_caret.repos
This modification is also incorporated into v0.6.2 tags.
[https://github.com/tier4/caret/pull/211](https://github.com/tier4/caret/pull/211)
=> fix: add topic_tools to the caret release script

ansible/roles/caret_iron/tasks/main.yml
Iron is now unsupported in ros2. As a result, the rosdep update does not work on the iron version of caret and the setup fails.
[https://tier4.atlassian.net/browse/RT2-2362](https://tier4.atlassian.net/browse/RT2-2362)
=> fix: rosdep update --include-eol-distros for iron

docker/build_autoware.dockerfile
- Agnocast has been introduced to Autoware. Agnocast is to be built but is not used by default
- However, CARET doesn't support Agnocast yet. It will be supported in a few months
- At the moment, Agnocast needs to be ignored to pass build
None
- Before (build error happens when building Agnocast)
- https://github.com/tier4/caret/actions/runs/14771035732/job/41471002491#step:3:12177
- After (build passed)
- https://github.com/tier4/caret/actions/runs/14772014419
=> ci: ignore Agnocast

docker/build_autoware.dockerfile
- Agnocast has been introduced to Autoware, but CARET doesn't support Agnocast yet. It causes build error
- Agnocast is not used by default, while it's part of the build
- Ignore (remove) Agnocast related code before starting build
Related PR: https://github.com/tier4/caret/pull/216
None
- Test result: https://github.com/tier4/caret/actions/runs/15896261297
- This change should be reverted when CARET officially support Agnocast
=> ci: ignore agnocast_wrapper
